import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // TS parameter properties (`constructor(readonly x: T)`) need a
      // type-aware transform to erase and silently break under plain
      // `node --experimental-strip-types` (strip-only mode, no type info) --
      // that's how every DB-touching lib module ran with tests for years
      // before scope.ts's AccessError hit it. Ban the shorthand outright so
      // it can't come back; see scope.ts's own comment on the fix.
      "@typescript-eslint/parameter-properties": ["error", { prefer: "class-property" }],
    },
  },
  {
    // next-env.d.ts is regenerated by Next itself and carries its own
    // "should not be edited" notice -- nothing to lint there.
    ignores: [".next/**", "node_modules/**", "drizzle/**", "next-env.d.ts"],
  },
];

export default eslintConfig;
